### POST
curl --request POST \
  --url https://dev-3t5ty0xt0strvi24.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"JewC0YOr3vgZrMePbQZhVHG87osgGgzq","client_secret":"dt8K6tpWk4tctivOKzDOcSDbf4-GMa_7N1ChDptx-1Tdwz0_eLA86Fyn_1S69EBN","audience":"https://Flying-Nomad/","grant_type":"client_credentials"}'
  
### GET
curl --request GET \
  --url http://localhost:5075/catalog/2 \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldjQ3VuZVRGbzVJRHB6eWpONDVxbCJ9.eyJpc3MiOiJodHRwczovL2Rldi0zdDV0eTB4dDBzdHJ2aTI0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKZXdDMFlPcjN2Z1pyTWVQYlFaaFZIRzg3b3NnR2d6cUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9GbHlpbmctTm9tYWQvIiwiaWF0IjoxNzQ1MTc3NzMyLCJleHAiOjE3NDUyNjQxMzIsInNjb3BlIjoiZGVsZXRlOmNhdGFsb2ciLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJKZXdDMFlPcjN2Z1pyTWVQYlFaaFZIRzg3b3NnR2d6cSJ9.cNtl0m5mTB3lqKko6nWYJofR9sc6yMysMFlOIquNbFmP-FW3wIQFwiHe_InchlUKJ3I8zB0c16Sdu9KVDBdTfBxe2Z5UVilq6QwVxybqcPXuVy0wnoCNb9ivDJrW-UDm9uRk3IXEgS8-LP2UObLaJTpy_Q990ZKzA9FQ9V59Dr5iXUuh2wMRWJwcn9AQ03OK9C5aUSNFFXPuCQTT6m-QKWQJVdnlvgq45yNlt_HRPiIqhIAoH3ytDq1KG5dAgf1azvZvCm4HNU-dBy__ik9YadqcAD3eriGm-uLV81MNhyWaTsANLRUxawK__EmfFZ82NTzX_sLB47_6QCtMbUk-2w'

### DELETE
curl --request DELETE \
  --url http://localhost:5075/catalog/2 \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldjQ3VuZVRGbzVJRHB6eWpONDVxbCJ9.eyJpc3MiOiJodHRwczovL2Rldi0zdDV0eTB4dDBzdHJ2aTI0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKZXdDMFlPcjN2Z1pyTWVQYlFaaFZIRzg3b3NnR2d6cUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9GbHlpbmctTm9tYWQvIiwiaWF0IjoxNzQ1MTc3NzMyLCJleHAiOjE3NDUyNjQxMzIsInNjb3BlIjoiZGVsZXRlOmNhdGFsb2ciLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJKZXdDMFlPcjN2Z1pyTWVQYlFaaFZIRzg3b3NnR2d6cSJ9.cNtl0m5mTB3lqKko6nWYJofR9sc6yMysMFlOIquNbFmP-FW3wIQFwiHe_InchlUKJ3I8zB0c16Sdu9KVDBdTfBxe2Z5UVilq6QwVxybqcPXuVy0wnoCNb9ivDJrW-UDm9uRk3IXEgS8-LP2UObLaJTpy_Q990ZKzA9FQ9V59Dr5iXUuh2wMRWJwcn9AQ03OK9C5aUSNFFXPuCQTT6m-QKWQJVdnlvgq45yNlt_HRPiIqhIAoH3ytDq1KG5dAgf1azvZvCm4HNU-dBy__ik9YadqcAD3eriGm-uLV81MNhyWaTsANLRUxawK__EmfFZ82NTzX_sLB47_6QCtMbUk-2w'
